### ISSUE TITLE
Search not available

### ISSUE THREAD

**Issue by Jeremy-JJ** [MarconiGRF/YTGameBarOverlay#15]
Good afternoon,

I have recently become interested in this project, given the profound convenience of being able to view a YouTube video, such as guides, while gaming.

The application works wonderfully and perfectly suits my needs. However, the only problem is the inability to search. It also appears as though the application is not storing previous searches. I can do without search history, but I cannot go without the search function.

The error I receive is "Search is not available now! Use links or try again."

I'm willing to help update the code, if it's something simple to fix.

Thank you,
Jeremy

**Comment by MarconiGRF** [comment]
Hey Jeremy! Sorry for the enormous delay to answer.

The search feature works with the [YTGBSearchServer](https://github.com/MarconiGRF/YTGameBarSearchServer) implementation. Currently it works (or used to work) using an YT search scrape library, unfortunately the YT platform is constantly changing and this makes it hard to keep features like this working consistently.

One thing that I was planning to implement is the official [YT Search API](https://developers.google.com/youtube/v3/docs/search/list) on YTGBSS mentioned above. The service exists solely for this purpose due that YTGBO widget needs the search results in a very specific schematic (like [this one in C#](https://github.com/MarconiGRF/YTGameBarOverlay/blob/e46bd3b42dd950d0ed6c1aa9787fa9ad41a80681/Search/Search.cs#L99C1-L106C56) or [this one in JavaScript](https://github.com/MarconiGRF/YTGameBarSearchServer/blob/76463ef5d5fa365c805749471f036405ba2a6e82/ytgbss.js#L95C1-L101C10)) so it can build the elements on the UI list.

It requires some effort to fix it, and unfortunately I'm short on time to work on this issue as of now, but once the results are in the format above I can release a fix on the MS store.
